const LANGUAGES_LETTERS_SHAPES = [
  {
    id: 1,
    language: "Urdu",
    gameLink: "urdu_game",
    lettersTitle:"???",
    LettersObject: [
      {
        id: 1,
        letter: "Alif",
        symbol: "الف",
        isolatedForm: "ا",
        initialForm: "آ",
        medialForm: "ـاـ",
        finalForm: "",
      },
      {
        id: 2,
        letter: "Bay",
        symbol: "بے",
        isolatedForm: "ب",
        initialForm: "بـ",
        medialForm: "ـبـ",
        finalForm: "ـب",
      },
      {
        id: 3,
        letter: "Pay",
        symbol: "پے",
        isolatedForm: "پ",
        initialForm: "پـ",
        medialForm: "ـپـ",
        finalForm: "ـپ",
      },
      {
        id: 4,
        letter: "Tay",
        symbol: "ٹے",
        isolatedForm: "ٹ",
        initialForm: "ٹـ",
        medialForm: "ـٹـ",
        finalForm: "ـٹ",
      },
      {
        id: 5,
        letter: "Tay with a dot",
        symbol: "ٹے",
        isolatedForm: "ٹ",
        initialForm: "ٹـ",
        medialForm: "ـٹـ",
        finalForm: "ـٹ",
      },
      {
        id: 6,
        letter: "Say",
        symbol: "ثے",
        isolatedForm: "ث",
        initialForm: "ثـ",
        medialForm: "ـثـ",
        finalForm: "ـث",
      },
      {
        id: 7,
        letter: "Jeem",
        symbol: "جیم",
        isolatedForm: "ج",
        initialForm: "جـ",
        medialForm: "ـجـ",
        finalForm: "ـج",
      },
      {
        id: 8,
        letter: "Che",
        symbol: "چے",
        isolatedForm: "چ",
        initialForm: "چـ",
        medialForm: "ـچـ",
        finalForm: "ـچ",
      },
      {
        id: 9,
        letter: "Hay",
        symbol: "حے",
        isolatedForm: "ح",
        initialForm: "حـ",
        medialForm: "ـحـ",
        finalForm: "ـح",
      },
      {
        id: 10,
        letter: "Khay",
        symbol: "خے",
        isolatedForm: "خ",
        initialForm: "خـ",
        medialForm: "ـخـ",
        finalForm: "ـخ",
      },
      {
        id: 11,
        letter: "Dal",
        symbol: "د",
        isolatedForm: "د",
        initialForm: "د",
        medialForm: "د",
        finalForm: "د",
      },
      {
        id: 12,
        letter: "DalD",
        symbol: "ڈ",
        isolatedForm: "ڈ",
        initialForm: "ڈـ",
        medialForm: "ـڈـ",
        finalForm: "ـڈ",
      },
            {
        id: 13,
        letter: "Zaal",
        symbol: "ذ",
        isolatedForm: "ذ",
        initialForm: "ذـ",
        medialForm: "ـذـ",
        finalForm: "ـذ",
      },
           {
        id: 14,
        letter: "Ray",
        symbol: "ر",
        isolatedForm: "ر",
        initialForm: "ر",
        medialForm: "ر",
        finalForm: "ر",
      },
            {
        id: 15,
        letter: "RayD",
        symbol: "ڑ",
        isolatedForm: "ڑ",
        initialForm: "ڑـ",
        medialForm: "ـڑـ",
        finalForm: "ـڑ",
      },
      {
        id: 16,
        letter: "Zay",
        symbol: "ز",
        isolatedForm: "ز",
        initialForm: "زـ",
        medialForm: "ـزـ",
        finalForm: "ـز",
      },
      {
        id: 17,
        letter: "Zwaad",
        symbol: "ژ",
        isolatedForm: "ژ",
        initialForm: "ژـ",
        medialForm: "ـژـ",
        finalForm: "ـژ",
      },
      {
        id: 18,
        letter: "Seen",
        symbol: "س",
        isolatedForm: "س",
        initialForm: "سـ",
        medialForm: "ـسـ",
        finalForm: "ـس",
      },
      {
        id: 19,
        letter: "Sheen",
        symbol: "ش",
        isolatedForm: "ش",
        initialForm: "شـ",
        medialForm: "ـشـ",
        finalForm: "ـش",
      },
      
      {
        id: 20,
        letter: "Suaad",
        symbol: "ص",
        isolatedForm: "ص",
        initialForm: "صـ",
        medialForm: "ـصـ",
        finalForm: "ـص",
      },
      {
        id: 21,
        letter: "Zuaad",
        symbol: "ض",
        isolatedForm: "ض",
        initialForm: "ضـ",
        medialForm: "ـضـ",
        finalForm: "ـض",
      },
      {
        id: 22,
        letter: "Toay",
        symbol: "ط",
        isolatedForm: "ط",
        initialForm: "طـ",
        medialForm: "ـطـ",
        finalForm: "ـط",
      },
      {
        id: 23,
        letter: "Zoay",
        symbol: "ظ",
        isolatedForm: "ظ",
        initialForm: "ظـ",
        medialForm: "ـظـ",
        finalForm: "ـظ",
      },
      {
        id: 24,
        letter: "Ain",
        symbol: "ع",
        isolatedForm: "ع",
        initialForm: "عـ",
        medialForm: "ـعـ",
        finalForm: "ـع",
      },
      {
        id: 25,
        letter: "Ghain",
        symbol: "غ",
        isolatedForm: "غ",
        initialForm: "غـ",
        medialForm: "ـغـ",
        finalForm: "ـغ",
      },
      {
        id: 26,
        letter: "Fay",
        symbol: "ف",
        isolatedForm: "ف",
        initialForm: "فـ",
        medialForm: "ـفـ",
        finalForm: "ـف",
      },
      {
        id: 27,
        letter: "Qaaf",
        symbol: "ق",
        isolatedForm: "ق",
        initialForm: "قـ",
        medialForm: "ـقـ",
        finalForm: "ـق",
      },
      {
        id: 28,
        letter: "Kaaf",
        symbol: "ک",
        isolatedForm: "ک",
        initialForm: "کـ",
        medialForm: "ـکـ",
        finalForm: "ـک",
      },
      {
        id: 29,
        letter: "Gaaf",
        symbol: "گ",
        isolatedForm: "گ",
        initialForm: "گـ",
        medialForm: "ـگـ",
        finalForm: "ـگ",
      },
      {
        id: 30,
        letter: "Laam",
        symbol: "ل",
        isolatedForm: "ل",
        initialForm: "لـ",
        medialForm: "ـلـ",
        finalForm: "ـل",
      },
      {
        id: 31,
        letter: "Meem",
        symbol: "م",
        isolatedForm: "م",
        initialForm: "مـ",
        medialForm: "ـمـ",
        finalForm: "ـم",
      },
      {
        id: 32,
        letter: "Noon",
        symbol: "ن",
        isolatedForm: "ن",
        initialForm: "نـ",
        medialForm: "ـنـ",
        finalForm: "ـن",
      },
      {
        id: 33,
        letter: "Wow",
        symbol: "و",
        isolatedForm: "و",
        initialForm: "و",
        medialForm: "و",
        finalForm: "و",
      },
      {
        id: 34,
        letter: "Choti He",
        symbol: "ہ",
        isolatedForm: "ہ",
        initialForm: "ہـ",
        medialForm: "ـہـ",
        finalForm: "ـہ",
      },
      {
        id: 35,
        letter: "Ye",
        symbol: "ی",
        isolatedForm: "ی",
        initialForm: "یـ",
        medialForm: "ـیـ",
        finalForm: "ـی",
      },
      {
        id: 36,
        letter: "Baari Ye",
        symbol: "ے",
        isolatedForm: "ے",
        initialForm: "ےـ",
        medialForm: "ـےـ",
        finalForm: "ـے",
      },
      {
        id: 37,
        letter: "Hamza",
        symbol: "ء",
        isolatedForm: "ء",
        initialForm: "",
        medialForm: "",
        finalForm: "",
      },
      {
        id: 38,
        letter: "Choti Yeh",
        symbol: "ۓ",
        isolatedForm: "ۓ",
        initialForm: "ۓـ",
        medialForm: "ـۓـ",
        finalForm: "ـۓ",
      },
      {
        id: 39,
        letter: "HeD",
        symbol: "ھ",
        isolatedForm: "ھ",
        initialForm: "ھـ",
        medialForm: "ـھـ",
        finalForm: "ـھ",
      }
    ],
  },
  {
    id: 2,
    language: "Arabic",
    gameLink: "arabic_game",
    LettersObject: [
      {
        id: 1,
        Letter: "elif",
        Symbol: "ا",
      },
      {
        id: 2,
        Letter: "be",
        Symbol: "ب",
      },
      {
        id: 3,
        Letter: "te",
        Symbol: "ت",
      },
      {
        id: 4,
        Letter: "tha’",
        Symbol: "ث",
      },
      {
        id: 5,
        Letter: "jīm",
        Symbol: "ج",
      },
      {
        id: 6,
        Letter: "ḥā’",
        Symbol: "ح",
      },
      {
        id: 7,
        Letter: "khā’",
        Symbol: "خ",
      },
      {
        id: 8,
        Letter: "dāl",
        Symbol: "د",
      },
      {
        id: 9,
        Letter: "dhāl",
        Symbol: "ذ",
      },
      {
        id: 10,
        Letter: "rā’",
        Symbol: "ر",
      },
      {
        id: 11,
        Letter: "zāy",
        Symbol: "ز",
      },
      {
        id: 12,
        Letter: "sīn",
        Symbol: "س",
      },
      {
        id: 13,
        Letter: "shīn",
        Symbol: "ش",
      },
      {
        id: 14,
        Letter: "ṣād",
        Symbol: "ص",
      },
      {
        id: 15,
        Letter: "ẓā’",
        Symbol: "ظ",
      },
      {
        id: 16,
        Letter: "‘ayn",
        Symbol: "ع",
      },
      {
        id: 17,
        Letter: "ghayn",
        Symbol: "غ",
      },
      {
        id: 18,
        Letter: "fā’",
        Symbol: "ف",
      },
      {
        id: 19,
        Letter: "qāf",
        Symbol: "ق",
      },
      {
        id: 20,
        Letter: "kāf",
        Symbol: "ك",
      },
      {
        id: 21,
        Letter: "lām",
        Symbol: "ل",
      },
      {
        id: 22,
        Letter: "mīm",
        Symbol: "م",
      },
      {
        id: 23,
        Letter: "nūn",
        Symbol: "ن",
      },
      {
        id: 24,
        Letter: "hā’",
        Symbol: "ه",
      },
      {
        id: 25,
        Letter: "wāw",
        Symbol: "و",
      },
      {
        id: 26,
        Letter: "yā’",
        Symbol: "ي",
      },
    ],
  },
  {
    id: 3,
    language: "Farsi",
    gameLink: "farsi_game",
    LettersObject: [
      {
        id: 1,
        Letter: "hamze",
        Symbol: "ه",
      },
      {
        id: 2,
        Letter: "ʾalef",
        Symbol: "ا",
      },
      {
        id: 3,
        Letter: "be",
        Symbol: "ب",
      },
      {
        id: 4,
        Letter: "pe",
        Symbol: "پ",
      },
      {
        id: 5,
        Letter: "te",
        Symbol: "ت",
      },
      {
        id: 6,
        Letter: "s̱e",
        Symbol: "ث",
      },
      {
        id: 7,
        Letter: "jim",
        Symbol: "ج",
      },
      {
        id: 8,
        Letter: "če",
        Symbol: "چ",
      },
      {
        id: 9,
        Letter: "ḥe ",
        Symbol: "ح",
      },
      {
        id: 10,
        Letter: "xe",
        Symbol: "خ",
      },
      {
        id: 11,
        Letter: "dâl",
        Symbol: "د",
      },
      {
        id: 12,
        Letter: "ẕâl",
        Symbol: "ذ",
      },
      {
        id: 13,
        Letter: "re",
        Symbol: "ر",
      },
      {
        id: 14,
        Letter: "ze",
        Symbol: "ز",
      },
      {
        id: 15,
        Letter: "že",
        Symbol: "ژ",
      },
      {
        id: 16,
        Letter: "sin",
        Symbol: "س",
      },
      {
        id: 17,
        Letter: "šin",
        Symbol: "ش",
      },
      {
        id: 18,
        Letter: "ṣâd",
        Symbol: "ص",
      },
      {
        id: 19,
        Letter: "zâd",
        Symbol: "ض",
      },
      {
        id: 20,
        Letter: "tâ",
        Symbol: "ط",
      },
      {
        id: 21,
        Letter: "ẓâ",
        Symbol: "ظ",
      },
      {
        id: 22,
        Letter: "ʿayn ",
        Symbol: "ع",
      },
      {
        id: 23,
        Letter: "ġayn",
        Symbol: "غ",
      },
      {
        id: 24,
        Letter: "fe",
        Symbol: "ف",
      },
      {
        id: 25,
        Letter: "qâf",
        Symbol: "ق",
      },
      {
        id: 26,
        Letter: "kâf",
        Symbol: "ک",
      },
      {
        id: 27,
        Letter: "gâf",
        Symbol: "گ",
      },
      {
        id: 28,
        Letter: "lâm",
        Symbol: "ل",
      },
      {
        id: 29,
        Letter: "mim",
        Symbol: "م",
      },
      {
        id: 30,
        Letter: "nun",
        Symbol: "ن",
      },
      {
        id: 31,
        Letter: "vâv",
        Symbol: "و",
      },
      {
        id: 32,
        Letter: "he",
        Symbol: "ه",
      },
      {
        id: 33,
        Letter: "ye",
        Symbol: "ی",
      },
    ],
    properties as needed
  },
];

export default LANGUAGES_LETTERS_SHAPES;
