const LANGUAGES_LETTERS_SHAPES = [
  {
    id: 1,
    language: "Urdu",
    gameLink: "urdu_game",
    lettersTable: "urdu_letters_table",
    mainTitle: "اردو",
    color: "#14de5e",
    cardTitle: "Learning Urdu letters?",
    longDescription:
      'In this table, you will find a comprehensive guide to understanding Urdu letters and their various forms. Each row provides valuable information about a specific letter. The "Letter" column denotes the name of the letter, while the "Symbol" column showcases its corresponding symbol or script. The "Isolated Form" column reveals the standalone form of the letter, while the "Initial Form" column displays its shape when it appears at the beginning of a word. The "Medial Form" column illustrates the letter\'s form in the middle of a word, and the "Final Form" column demonstrates how it appears at the end of a word. Explore this table to deepen your knowledge of Urdu letters and their unique forms.',
    smallDescription:
      "Discover Urdu letters and their forms in a comprehensive table, expanding your knowledge of this beautiful language.",
    LettersObject: [
      {
        id: 1,
        letter: "Alif",
        symbol: "الف",
        isolatedForm: "ا",
        initialForm: "آ",
        medialForm: "ـاـ",
        finalForm: "",
      },
      {
        id: 2,
        letter: "Bay",
        symbol: "بے",
        isolatedForm: "ب",
        initialForm: "بـ",
        medialForm: "ـبـ",
        finalForm: "ـب",
      },
      {
        id: 3,
        letter: "Pay",
        symbol: "پے",
        isolatedForm: "پ",
        initialForm: "پـ",
        medialForm: "ـپـ",
        finalForm: "ـپ",
      },
      {
        id: 4,
        letter: "Tay",
        symbol: "ٹے",
        isolatedForm: "ٹ",
        initialForm: "ٹـ",
        medialForm: "ـٹـ",
        finalForm: "ـٹ",
      },
      {
        id: 5,
        letter: "Tay with a dot",
        symbol: "ٹے",
        isolatedForm: "ٹ",
        initialForm: "ٹـ",
        medialForm: "ـٹـ",
        finalForm: "ـٹ",
      },
      {
        id: 6,
        letter: "Say",
        symbol: "ثے",
        isolatedForm: "ث",
        initialForm: "ثـ",
        medialForm: "ـثـ",
        finalForm: "ـث",
      },
      {
        id: 7,
        letter: "Jeem",
        symbol: "جیم",
        isolatedForm: "ج",
        initialForm: "جـ",
        medialForm: "ـجـ",
        finalForm: "ـج",
      },
      {
        id: 8,
        letter: "Che",
        symbol: "چے",
        isolatedForm: "چ",
        initialForm: "چـ",
        medialForm: "ـچـ",
        finalForm: "ـچ",
      },
      {
        id: 9,
        letter: "Hay",
        symbol: "حے",
        isolatedForm: "ح",
        initialForm: "حـ",
        medialForm: "ـحـ",
        finalForm: "ـح",
      },
      {
        id: 10,
        letter: "Khay",
        symbol: "خے",
        isolatedForm: "خ",
        initialForm: "خـ",
        medialForm: "ـخـ",
        finalForm: "ـخ",
      },
      {
        id: 11,
        letter: "Dal",
        symbol: "د",
        isolatedForm: "د",
        initialForm: "د",
        medialForm: "د",
        finalForm: "د",
      },
      {
        id: 12,
        letter: "DalD",
        symbol: "ڈ",
        isolatedForm: "ڈ",
        initialForm: "ڈـ",
        medialForm: "ـڈـ",
        finalForm: "ـڈ",
      },
      {
        id: 13,
        letter: "Zaal",
        symbol: "ذ",
        isolatedForm: "ذ",
        initialForm: "ذـ",
        medialForm: "ـذـ",
        finalForm: "ـذ",
      },
      {
        id: 14,
        letter: "Ray",
        symbol: "ر",
        isolatedForm: "ر",
        initialForm: "ر",
        medialForm: "ر",
        finalForm: "ر",
      },
      {
        id: 15,
        letter: "RayD",
        symbol: "ڑ",
        isolatedForm: "ڑ",
        initialForm: "ڑـ",
        medialForm: "ـڑـ",
        finalForm: "ـڑ",
      },
      {
        id: 16,
        letter: "Zay",
        symbol: "ز",
        isolatedForm: "ز",
        initialForm: "زـ",
        medialForm: "ـزـ",
        finalForm: "ـز",
      },
      {
        id: 17,
        letter: "Zwaad",
        symbol: "ژ",
        isolatedForm: "ژ",
        initialForm: "ژـ",
        medialForm: "ـژـ",
        finalForm: "ـژ",
      },
      ,
      {
        id: 18,
        letter: "Seen",
        symbol: "س",
        isolatedForm: "س",
        initialForm: "سـ",
        medialForm: "ـسـ",
        finalForm: "ـس",
      },
      {
        id: 19,
        letter: "Sheen",
        symbol: "ش",
        isolatedForm: "ش",
        initialForm: "شـ",
        medialForm: "ـشـ",
        finalForm: "ـش",
      },

      {
        id: 20,
        letter: "Suaad",
        symbol: "ص",
        isolatedForm: "ص",
        initialForm: "صـ",
        medialForm: "ـصـ",
        finalForm: "ـص",
      },
      {
        id: 21,
        letter: "Zuaad",
        symbol: "ض",
        isolatedForm: "ض",
        initialForm: "ضـ",
        medialForm: "ـضـ",
        finalForm: "ـض",
      },
      {
        id: 22,
        letter: "Toay",
        symbol: "ط",
        isolatedForm: "ط",
        initialForm: "طـ",
        medialForm: "ـطـ",
        finalForm: "ـط",
      },
      {
        id: 23,
        letter: "Zoay",
        symbol: "ظ",
        isolatedForm: "ظ",
        initialForm: "ظـ",
        medialForm: "ـظـ",
        finalForm: "ـظ",
      },
      {
        id: 24,
        letter: "Ain",
        symbol: "ع",
        isolatedForm: "ع",
        initialForm: "عـ",
        medialForm: "ـعـ",
        finalForm: "ـع",
      },
      {
        id: 25,
        letter: "Ghain",
        symbol: "غ",
        isolatedForm: "غ",
        initialForm: "غـ",
        medialForm: "ـغـ",
        finalForm: "ـغ",
      },
      {
        id: 26,
        letter: "Fay",
        symbol: "ف",
        isolatedForm: "ف",
        initialForm: "فـ",
        medialForm: "ـفـ",
        finalForm: "ـف",
      },
      {
        id: 27,
        letter: "Qaaf",
        symbol: "ق",
        isolatedForm: "ق",
        initialForm: "قـ",
        medialForm: "ـقـ",
        finalForm: "ـق",
      },
      {
        id: 28,
        letter: "Kaaf",
        symbol: "ک",
        isolatedForm: "ک",
        initialForm: "کـ",
        medialForm: "ـکـ",
        finalForm: "ـک",
      },
      {
        id: 29,
        letter: "Gaaf",
        symbol: "گ",
        isolatedForm: "گ",
        initialForm: "گـ",
        medialForm: "ـگـ",
        finalForm: "ـگ",
      },
      {
        id: 30,
        letter: "Laam",
        symbol: "ل",
        isolatedForm: "ل",
        initialForm: "لـ",
        medialForm: "ـلـ",
        finalForm: "ـل",
      },
      {
        id: 31,
        letter: "Meem",
        symbol: "م",
        isolatedForm: "م",
        initialForm: "مـ",
        medialForm: "ـمـ",
        finalForm: "ـم",
      },
      {
        id: 32,
        letter: "Noon",
        symbol: "ن",
        isolatedForm: "ن",
        initialForm: "نـ",
        medialForm: "ـنـ",
        finalForm: "ـن",
      },
      {
        id: 33,
        letter: "Wow",
        symbol: "و",
        isolatedForm: "و",
        initialForm: "و",
        medialForm: "و",
        finalForm: "و",
      },
      {
        id: 34,
        letter: "Choti He",
        symbol: "ہ",
        isolatedForm: "ہ",
        initialForm: "ہـ",
        medialForm: "ـہـ",
        finalForm: "ـہ",
      },
      {
        id: 35,
        letter: "Ye",
        symbol: "ی",
        isolatedForm: "ی",
        initialForm: "یـ",
        medialForm: "ـیـ",
        finalForm: "ـی",
      },
      {
        id: 36,
        letter: "Baari Ye",
        symbol: "ے",
        isolatedForm: "ے",
        initialForm: "ےـ",
        medialForm: "ـےـ",
        finalForm: "ـے",
      },
      {
        id: 37,
        letter: "Hamza",
        symbol: "ء",
        isolatedForm: "ء",
        initialForm: "",
        medialForm: "",
        finalForm: "",
      },
      {
        id: 38,
        letter: "Choti Yeh",
        symbol: "ۓ",
        isolatedForm: "ۓ",
        initialForm: "ۓـ",
        medialForm: "ـۓـ",
        finalForm: "ـۓ",
      },
      {
        id: 39,
        letter: "HeD",
        symbol: "ھ",
        isolatedForm: "ھ",
        initialForm: "ھـ",
        medialForm: "ـھـ",
        finalForm: "ـھ",
      },
    ],
  },
];
export default LANGUAGES_LETTERS_SHAPES;
